version: '3'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8080:80"
  
  words:
    build:
      context: ./words
      dockerfile: Dockerfile

  db:
    build:
      context: ./db
      dockerfile: Dockerfile