name: Build and Push Docker Images

on:
  pull_request:
    types:
      - labeled

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: lilshad/words-db
            directory: ./db
          - image: lilshad/words-web
            directory: ./web
          - image: lilshad/words-api
            directory: ./words
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
  
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    

      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v5.5.0
        with:
          images: ${{ matrix.image }}
    

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          context: ${{ matrix.directory }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

